#!/bin/sh

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

application_name="$(basename "$1")"

# Description: handle .apps or .game applications when trying to open them. Offer to install or simply run

#(gnome-terminal --tab --title="Neofetch" -- /bin/sh -c 'neofetch; exec bash' &)
#if user want to install: mv <folder-name> /1/apps

#if [ "$1" != "" ]; then
if [ "$(echo ${application_name##*.})" = "apps" ] || [ "$(echo ${application_name##*.})" = "game" ]; then
   mkdir /tmp/openned-floflis-applications
   mkdir /tmp/openned-floflis-applications/apps
   mkdir /tmp/openned-floflis-applications/games

   if [ "$(echo ${application_name##*.})" = "apps" ]; then
      open_tmp_path="/tmp/openned-floflis-applications/apps"
fi

   if [ "$(echo ${application_name##*.})" = "game" ]; then
      open_tmp_path="/tmp/openned-floflis-applications/games"
fi

   tar -C $open_tmp_path -xzf "$1"
   cd "$open_tmp_path/application"
   current_app="$(ls "$open_tmp_path/application")"
   cp -r -f --preserve=all . "$open_tmp_path"
   cd ..
   rm -r "application"
   cd "$current_app"
   floflis-packager c2 initpreview
   cd ..
   rm -r "$current_app"
else
   echo "---- Floflis Application Handler ----"
   echo "The file you tried to open isn't a Floflis application."
   echo "Floflis applications are .apps or .game files."
fi

if [ "$1" = "babyisalive" ]; then
   exit 0
fi
